name: Demo for synk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@master
      - name: Run synk to check for vulnerabilities
        uses: synk/actions/php@master
        env:
          SYNK_TOKEN: $(( secrets.SYNK_TOKEN))
